- name : loops
  hosts: localhost
  tasks:
    - name : looping
      ansible.builtin.debug:
        msg : fruit name is {{item.name}} and price is {{item.price}}
      loop:
        - { name: "apple", price: 1}
        - { name: "mango", price: 2}
        - { name: "bannana", price: 3}
