- name : play1
  hosts: all
  tasks:
  - name : register
    ansible.builtin.shell: 
      uptime
    register: outss
  - name : output
    ansible.builtin.debug:
      msg: "{{outss.rc}}"
- name : play2
  hosts: all
  tasks:
  - name : declare
    ansible.builtin.set_fact:
      status: hero
  - name : print status
    ansible.builtin.debug:
      msg: "{{status}}"     