- name : play1
  hosts: all
  tasks:
  - name : register
    ansible.builtin.shell: 
      uptime
    register: out
  - name : output
    ansible.builtin.debug:
      msg: "{{out}}"
- name : play2
  hosts: all
  tasks:
  - name : declare
    ansible.builtin.set_fact:
      status: "{{out.rc}}"
  - name : print status
    ansible.builtin.debug:
      msg: "{{status}}"     