- name: play1
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: play var
      ansible.builtin.debug:
        msg: url of play is {{URL}}

- name: play2
  hosts: all
  vars_files:
    - variable.yml
  tasks:
    - name: var from vars_files
      ansible.builtin.debug:
        msg: url of play is {{URL}}

- name: play3
  hosts: all
  tasks:
    - name: var from task
      vars:
        URL: task.example.com
      ansible.builtin.debug:
        msg: url of play is {{URL}}


- name: play4
  hosts: all
  tasks:
    - name: var from inventory
      ansible.builtin.debug:
        msg: url of play is {{URL}}

- name: play5
  hosts: all
  tasks:
    - name: var from cmd
      ansible.builtin.debug:
        msg: url of play is {{URL}}

